language: node_js
node_js:
  - node
script:
  - npm run lint
  - npm test
deploy:
  provider: heroku
  app: api-daktary
  api_key:
    secure: BrePPL7Gx/Vf9P9UZwZcub5Bo3n7D0FhiE+2YOeV5DCTL27nvT/2oesKz8nAho60YcLAHaGLOsLpILlLchDNefNFt83elQv85vcSaaaAIi4/u+YODdDiqzmxH3GPoGVz0lxQ52Sd83F1C3O+Ails1tNwSw9YW3Fp5YJ4wIhIgTwvEStzdi9GCUZm5vp8QTFuDkl6J2mcMYj7r3p4r8m3kcBBlC55jhYopJE7Jb0BwYeHYXlN+nMcu2/gWZF2Acf41S3qoKkOezUi/ZYxQAuk9woAFzwGqELE59g9neao+NS5/h04bLZw5qmzam/JNvHVGrA6rFVJGbT1WgI05j/injFsOVElv1sYd82sBpiAZJzY3xkIl2QbLWs9UR8d7KCR9BMyIhrXqwCgp1yMCa/qg6kAaOvouvUyjl54fVHKIlt2O8O2CQDbGwBh7EyS5ojrLlLkThb45W7Cfi0pbggHWRETTa91Af2PhCkC3iKPNimUnEjBpblstkY4cCFnc4qkanSMl4zIPyNUtWMVQ1qu4ZOGORWlehjPc2pseVPdFEmnp1lz6dp8UcdSmPthi997ATRAGxcGYfDzUc7E0dJK4v+hMBqFRY6WAFoc3bm/umrj0ZtG9Un7vns0+QIoneqIaVgYLR1PWgJsvrs77WY4xf7KUolzvV0zJtdkL9RyP8M=
  on:
    branch: master
